theme = 'schmoklos'
baseURL = 'http://shmulik-klein.github.io/'
languageCode = 'en-us'
title = 'Shmulik Klein | Blog'
relativeURLs = true
enableEmoji = true
copyright = "&copy; Copyright 2025, Shmulik Klein"
googleAnalytics = "G-1LHXLEKFK2"

[sitemap]
  changefreq = "weekly"
  priority = 0.5
  filename = "sitemap.xml"
  ignoreFiles = ["404.html"]
  [sitemap.custom]
    template = "sitemap/sitemap.xml"

[taxonomies]
  category = 'categories'
  series = 'series'
  tag = 'tags'

[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    title = "About"
    url = "/about"
    weight = -110
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    title = "Posts"
    url = "/posts/"
    weight = -100
  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    title = "Tags"
    url = "/tags/"
    weight = -100
  [[menu.main]]
    identifier = "categories"
    name = "Categories"
    title = "Categories"
    url = "/categories/"
    weight = -90
  [[menu.main]]
    identifier = "series"
    name = "Series"
    title = "Series"
    url = "/series/"
    weight = -80

[params]
  description = "My [Shmulik Klein] blog, about softeware engineering topics" # the <meta name="description"> tag
  header_title = "Shmulik Klein" # The header title
  header_subtitle = "Software Engineer @ JetBrains | Munich, Germany"
  home_image = "logo.jpeg"          # Path to header image starting from the static directory
  recent_posts = 5                           # Max amount of recent posts to show
  mainSections = ["posts"]   # Main sections to include in recent posts
  [params.style]                             # CSS style overrides
    backgroundColor = "#f8f9fa"
    fontColor = "#212529"
  [[params.social]]
    name="Github Link"
    fa_icon = "fab fa-github fa-1x"
    href = "http://github.com/shmulik-klein"
  [[params.social]]
    name="Facebook Link"
    fa_icon = "fab fa-linkedin-in fa-1x"
    href = "https://www.linkedin.com/in/shmulik-klein/?lipi=urn%3Ali%3Apage%3Ad_flagship3_feed%3BuBzQ49WXS3K1iGjTur%2Fycw%3D%3D"
  [[params.social]]
    name="StackOverflow Link"
    fa_icon = "fab fa-stack-overflow"
    href = "https://stackoverflow.com/users/2776473/shmulik-klein"
  [[params.social]]
    name="X Link"
    fa_icon = "fab fa-x-twitter fa-1x"
    href = "https://x.com/klein_sh"
  [[params.social]]
    name="E-mail Link"
    fa_icon = "fas fa-envelope fa-1x"
    href = "mailto:shmulik-klein@gmail.com"